name: AccuLightwellness
favicon: null
layout_spectrum: 0.9303320730105042
typography_spectrum: 0.8898595804348588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19377625384368002
  lightness: 0.9424849695060402
  saturation: 0.866107395850122
  rhythmicContrast: 0.116678511723876
purpose: []
